import { mkdtempSync, rmSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { describe, expect, it } from 'vitest'; import { ContainmentService } from '../src/domain.mjs'; import { AtomicStore } from '../src/store.mjs';
class MemoryStore { constructor() { this.database = { containments: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-812', role: 'evidence_owner' }; const input = { supplierId: 'SUP-812', evidenceReference: 'EVD-812', scope: 'Suspend external evidence access pending containment verification', containmentType: 'access_suspension' }; const chain = [{ action: 'plan', role: 'containment_planner' }, { action: 'verifyExecution', role: 'execution_verifier' }, { action: 'validateEffectiveness', role: 'effectiveness_validator' }, { action: 'authorize', role: 'containment_authority' }, { action: 'close', role: 'containment_registrar' }];
describe('ContainmentService', () => {
  it('records a complete independently controlled containment lifecycle', () => { const store = new MemoryStore(); const service = new ContainmentService(store); let containment = service.submit(input, owner, 'request-submit-812'); for (const step of chain) containment = service.transition(containment.id, step.action, { note: `${step.action} completed` }, { id: step.role, role: step.role }, `request-${step.action}-812`); expect(containment.status).toBe('closed'); expect(containment.events.map((event) => event.type)).toContain('containment_closed'); expect(store.writes).toBe(6); });
  it('rejects invalid containment types before persistence', () => { const store = new MemoryStore(); const service = new ContainmentService(store); expect(() => service.submit({ ...input, containmentType: 'other' }, owner, 'request-invalid-812')).toThrow('containment type is invalid'); expect(store.writes).toBe(0); });
  it('preserves state when an actor lacks the required role', () => { const store = new MemoryStore(); const service = new ContainmentService(store); const containment = service.submit(input, owner, 'request-role-812'); expect(() => service.transition(containment.id, 'plan', { note: 'attempt' }, owner, 'request-role-denied-812')).toThrow('role containment_planner is required'); expect(service.get(containment.id).status).toBe('submitted'); expect(store.writes).toBe(1); });
  it('creates an empty collection when the data file is absent', () => { const directory = mkdtempSync(join(tmpdir(), 'containment-assurance-')); try { const store = new AtomicStore(join(directory, 'data', 'containments.json')); expect(store.read()).toEqual({ containments: [] }); store.write({ containments: [] }); expect(store.read()).toEqual({ containments: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
